[links]
pulseaudio = "~/.config/pulseaudio-ctl/config"
kglobalshortcutsrc = "~/.config/kglobalshortcutsrc"
ranger = "~/.config/ranger/rc.conf"
sxhkdrc = "~/.config/sxhkd/sxhkdrc"
"tmux.conf.local" = "~/.tmux.conf.local"
xmodmap = "~/.xmodmap"
"polybar/" = "~/.config/polybar"
"fish/" = "~/.config/fish"
rofi = "~/.config/rofi/config"
khotkeysrc = "~/.config/khotkeysrc"
"set_window_manager.sh" = "~/.config/plasma-workspace/env/set_window_manager.sh"
xprofile = "~/.xprofile"
dunstrc = "~/.config/dunst/dunstrc"
"tmux/.tmux.conf" = "~/.tmux.conf"
vimrc = "~/.vimrc"
